# Generated by Django 6.0 on 2026-01-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('core', 'Core'), ('hero', 'Hero'), ('lord', 'Lord'), ('special', 'Special'), ('rare', 'Rare')], max_length=10)),
                ('points', models.PositiveIntegerField()),
                ('min_size', models.PositiveIntegerField(default=5)),
                ('max_size', models.PositiveIntegerField(default=20)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.faction')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['faction', 'name', 'role'],
            },
        ),
    ]
