# Generated by Django 4.2.27 on 2026-01-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
