# Generated by Django 4.2.27 on 2026-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
