# Generated by Django 4.2.27 on 2026-01-21 09:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unit_image_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
