# Generated by Django 6.0 on 2026-01-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_unit_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('point_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='army_lists', to='core.faction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Army List',
                'verbose_name_plural': 'Army Lists',
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='ListUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=5)),
                ('subtotal_points', models.PositiveIntegerField(default=0)),
                ('army_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_units', to='lists.armylist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_units', to='core.unit')),
            ],
            options={
                'verbose_name': 'List Unit',
                'verbose_name_plural': 'List Units',
                'ordering': ['army_list', 'unit__faction', 'unit__name'],
            },
        ),
        migrations.AddIndex(
            model_name='armylist',
            index=models.Index(fields=['owner', 'faction'], name='lists_armyl_owner_i_18342b_idx'),
        ),
    ]
