# Generated by Django 4.2.27 on 2026-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listunit',
            name='unit_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
